[workspace]
members = [
    "bunpo",
    "jmdict-fast",
    "jmdict-fast-bolt",
    "jmdict-fast-ffi",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.1.5"
edition = "2021"
authors = ["Glenn Sonna <theGlenn@users.noreply.github.com>"]
license = "MIT"
repository = "https://github.com/theGlenn/jmdict-fst"
