/// Flutter/Dart bindings for jmdict-fast.
///
/// The actual binding code in `src/` is generated by
/// `flutter_rust_bridge_codegen generate`. Run the codegen from the Rust
/// crate root (the parent directory of this Dart package) — see the
/// repository README for details. Until then this file is a placeholder.
///
/// Once generation has run, replace this file's contents with:
///
/// ```dart
/// export 'src/rust/api/dictionary.dart';
/// export 'src/rust/api/error.dart';
/// export 'src/rust/api/model.dart';
/// export 'src/rust/frb_generated.dart';
/// ```
///
/// or whatever paths the generator emits. The exact paths depend on the
/// `dart_output` setting in `flutter_rust_bridge.yaml`.
library;
