// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dictionary.dart';
import 'api/error.dart';
import 'api/install.dart';
import 'api/model.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 63043052;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'jmdict_fast_flutter',
    ioDirectory: '../target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<BigInt> crateApiDictionaryDictEntryCount({required Dict that});

  Future<Entry?> crateApiDictionaryDictGet(
      {required Dict that, required BigInt seqId});

  Future<Dict> crateApiDictionaryDictInstall();

  Future<Dict> crateApiDictionaryDictInstallFromTarball({required String path});

  Future<Dict> crateApiDictionaryDictInstallFromUrl({required String url});

  Future<Dict> crateApiDictionaryDictInstallWith(
      {required InstallOptions options});

  Future<List<Entry>> crateApiDictionaryDictIterEntries(
      {required Dict that, required BigInt start, required BigInt count});

  Future<Dict> crateApiDictionaryDictLoad({required String path});

  Future<Dict> crateApiDictionaryDictLoadDefault();

  Future<List<BatchResult>> crateApiDictionaryDictLookupBatch(
      {required Dict that,
      required List<String> terms,
      required QueryOptions options});

  Future<LookupResult?> crateApiDictionaryDictLookupById(
      {required Dict that, required String jmdictId});

  Future<List<LookupResult>> crateApiDictionaryDictLookupExact(
      {required Dict that, required String term});

  Future<List<LookupResult>> crateApiDictionaryDictLookupExactWithDeinflection(
      {required Dict that, required String term});

  Future<List<LookupResult>> crateApiDictionaryDictLookupGloss(
      {required Dict that, required String query});

  Future<List<LookupResult>> crateApiDictionaryDictLookupPartial(
      {required Dict that, required String prefix});

  Future<List<LookupResult>> crateApiDictionaryDictLookupWithOptions(
      {required Dict that,
      required String term,
      required QueryOptions options});

  Future<List<LookupResult>> crateApiDictionaryDictResolveXref(
      {required Dict that, required Xref xref});

  Future<DataVersion> crateApiDictionaryDictVersion({required Dict that});

  Future<void> crateApiInstallInitSdkCacheDir({required String path});

  Future<InstallOptions> crateApiInstallInstallOptionsDefault();

  Future<InstallSource> crateApiInstallInstallSourceDefault();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Dict;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Dict;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DictPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BigInt> crateApiDictionaryDictEntryCount({required Dict that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictEntryCountConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictEntryCountConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_entry_count",
        argNames: ["that"],
      );

  @override
  Future<Entry?> crateApiDictionaryDictGet(
      {required Dict that, required BigInt seqId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_u_64(seqId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_entry,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictGetConstMeta,
      argValues: [that, seqId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictGetConstMeta => const TaskConstMeta(
        debugName: "Dict_get",
        argNames: ["that", "seqId"],
      );

  @override
  Future<Dict> crateApiDictionaryDictInstall() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictInstallConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictInstallConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_install",
        argNames: [],
      );

  @override
  Future<Dict> crateApiDictionaryDictInstallFromTarball(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictInstallFromTarballConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictInstallFromTarballConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_install_from_tarball",
        argNames: ["path"],
      );

  @override
  Future<Dict> crateApiDictionaryDictInstallFromUrl({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictInstallFromUrlConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictInstallFromUrlConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_install_from_url",
        argNames: ["url"],
      );

  @override
  Future<Dict> crateApiDictionaryDictInstallWith(
      {required InstallOptions options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_install_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictInstallWithConstMeta,
      argValues: [options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictInstallWithConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_install_with",
        argNames: ["options"],
      );

  @override
  Future<List<Entry>> crateApiDictionaryDictIterEntries(
      {required Dict that, required BigInt start, required BigInt count}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_u_64(start, serializer);
        sse_encode_u_64(count, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_entry,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictIterEntriesConstMeta,
      argValues: [that, start, count],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictIterEntriesConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_iter_entries",
        argNames: ["that", "start", "count"],
      );

  @override
  Future<Dict> crateApiDictionaryDictLoad({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictLoadConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLoadConstMeta => const TaskConstMeta(
        debugName: "Dict_load",
        argNames: ["path"],
      );

  @override
  Future<Dict> crateApiDictionaryDictLoadDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictLoadDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLoadDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_load_default",
        argNames: [],
      );

  @override
  Future<List<BatchResult>> crateApiDictionaryDictLookupBatch(
      {required Dict that,
      required List<String> terms,
      required QueryOptions options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_list_String(terms, serializer);
        sse_encode_box_autoadd_query_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_batch_result,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictLookupBatchConstMeta,
      argValues: [that, terms, options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLookupBatchConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_lookup_batch",
        argNames: ["that", "terms", "options"],
      );

  @override
  Future<LookupResult?> crateApiDictionaryDictLookupById(
      {required Dict that, required String jmdictId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_String(jmdictId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_lookup_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictLookupByIdConstMeta,
      argValues: [that, jmdictId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLookupByIdConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_lookup_by_id",
        argNames: ["that", "jmdictId"],
      );

  @override
  Future<List<LookupResult>> crateApiDictionaryDictLookupExact(
      {required Dict that, required String term}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_String(term, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_lookup_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictLookupExactConstMeta,
      argValues: [that, term],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLookupExactConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_lookup_exact",
        argNames: ["that", "term"],
      );

  @override
  Future<List<LookupResult>> crateApiDictionaryDictLookupExactWithDeinflection(
      {required Dict that, required String term}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_String(term, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_lookup_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictLookupExactWithDeinflectionConstMeta,
      argValues: [that, term],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiDictionaryDictLookupExactWithDeinflectionConstMeta =>
          const TaskConstMeta(
            debugName: "Dict_lookup_exact_with_deinflection",
            argNames: ["that", "term"],
          );

  @override
  Future<List<LookupResult>> crateApiDictionaryDictLookupGloss(
      {required Dict that, required String query}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_String(query, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_lookup_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictLookupGlossConstMeta,
      argValues: [that, query],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLookupGlossConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_lookup_gloss",
        argNames: ["that", "query"],
      );

  @override
  Future<List<LookupResult>> crateApiDictionaryDictLookupPartial(
      {required Dict that, required String prefix}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_String(prefix, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_lookup_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictLookupPartialConstMeta,
      argValues: [that, prefix],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLookupPartialConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_lookup_partial",
        argNames: ["that", "prefix"],
      );

  @override
  Future<List<LookupResult>> crateApiDictionaryDictLookupWithOptions(
      {required Dict that,
      required String term,
      required QueryOptions options}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_String(term, serializer);
        sse_encode_box_autoadd_query_options(options, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_lookup_result,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiDictionaryDictLookupWithOptionsConstMeta,
      argValues: [that, term, options],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictLookupWithOptionsConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_lookup_with_options",
        argNames: ["that", "term", "options"],
      );

  @override
  Future<List<LookupResult>> crateApiDictionaryDictResolveXref(
      {required Dict that, required Xref xref}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        sse_encode_box_autoadd_xref(xref, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_lookup_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictResolveXrefConstMeta,
      argValues: [that, xref],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictResolveXrefConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_resolve_xref",
        argNames: ["that", "xref"],
      );

  @override
  Future<DataVersion> crateApiDictionaryDictVersion({required Dict that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_data_version,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDictionaryDictVersionConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDictionaryDictVersionConstMeta =>
      const TaskConstMeta(
        debugName: "Dict_version",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiInstallInitSdkCacheDir({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_error,
      ),
      constMeta: kCrateApiInstallInitSdkCacheDirConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallInitSdkCacheDirConstMeta =>
      const TaskConstMeta(
        debugName: "init_sdk_cache_dir",
        argNames: ["path"],
      );

  @override
  Future<InstallOptions> crateApiInstallInstallOptionsDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_install_options,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInstallInstallOptionsDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallInstallOptionsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "install_options_default",
        argNames: [],
      );

  @override
  Future<InstallSource> crateApiInstallInstallSourceDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_install_source,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInstallInstallSourceDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInstallInstallSourceDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "install_source_default",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Dict =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Dict =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict;

  @protected
  Dict
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DictImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Dict
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DictImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Dict
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DictImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BatchResult dco_decode_batch_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BatchResult(
      term: dco_decode_String(arr[0]),
      results: dco_decode_list_lookup_result(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeinflectionInfo dco_decode_box_autoadd_deinflection_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_deinflection_info(raw);
  }

  @protected
  Entry dco_decode_box_autoadd_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_entry(raw);
  }

  @protected
  InstallOptions dco_decode_box_autoadd_install_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_install_options(raw);
  }

  @protected
  LookupResult dco_decode_box_autoadd_lookup_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_lookup_result(raw);
  }

  @protected
  QueryOptions dco_decode_box_autoadd_query_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_query_options(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Xref dco_decode_box_autoadd_xref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_xref(raw);
  }

  @protected
  DataVersion dco_decode_data_version(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DataVersion(
      formatVersion: dco_decode_u_32(arr[0]),
      jmdictVersion: dco_decode_String(arr[1]),
      generatedAt: dco_decode_String(arr[2]),
    );
  }

  @protected
  DeinflectionInfo dco_decode_deinflection_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeinflectionInfo(
      originalForm: dco_decode_String(arr[0]),
      baseForm: dco_decode_String(arr[1]),
      rules: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  Entry dco_decode_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Entry(
      id: dco_decode_String(arr[0]),
      kanji: dco_decode_list_kanji_entry(arr[1]),
      kana: dco_decode_list_kana_entry(arr[2]),
      sense: dco_decode_list_sense_entry(arr[3]),
    );
  }

  @protected
  Error dco_decode_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Error_DataNotFound();
      case 1:
        return Error_DataVersionMismatch(
          expected: dco_decode_u_32(raw[1]),
          found: dco_decode_u_32(raw[2]),
        );
      case 2:
        return Error_DataCorrupted();
      case 3:
        return Error_InvalidQuery();
      case 4:
        return Error_Io(
          message: dco_decode_String(raw[1]),
        );
      case 5:
        return Error_Deserialization();
      case 6:
        return Error_CacheDirRequired(
          platform: dco_decode_String(raw[1]),
        );
      case 7:
        return Error_CacheDirAlreadySet();
      case 8:
        return Error_Network(
          message: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GlossEntry dco_decode_gloss_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GlossEntry(
      lang: dco_decode_String(arr[0]),
      gender: dco_decode_opt_String(arr[1]),
      glossType: dco_decode_opt_String(arr[2]),
      text: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InstallOptions dco_decode_install_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return InstallOptions(
      cacheDir: dco_decode_opt_String(arr[0]),
      source: dco_decode_install_source(arr[1]),
      force: dco_decode_bool(arr[2]),
    );
  }

  @protected
  InstallSource dco_decode_install_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return InstallSource_OfficialRelease();
      case 1:
        return InstallSource_Url(
          url: dco_decode_String(raw[1]),
        );
      case 2:
        return InstallSource_Tarball(
          path: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  KanaEntry dco_decode_kana_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return KanaEntry(
      common: dco_decode_bool(arr[0]),
      text: dco_decode_String(arr[1]),
      tags: dco_decode_list_String(arr[2]),
      appliesToKanji: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  KanjiEntry dco_decode_kanji_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KanjiEntry(
      common: dco_decode_bool(arr[0]),
      text: dco_decode_String(arr[1]),
      tags: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  LanguageSource dco_decode_language_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LanguageSource(
      lang: dco_decode_String(arr[0]),
      full: dco_decode_bool(arr[1]),
      wasei: dco_decode_bool(arr[2]),
      text: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BatchResult> dco_decode_list_batch_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_batch_result).toList();
  }

  @protected
  List<Entry> dco_decode_list_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry).toList();
  }

  @protected
  List<GlossEntry> dco_decode_list_gloss_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gloss_entry).toList();
  }

  @protected
  List<KanaEntry> dco_decode_list_kana_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_kana_entry).toList();
  }

  @protected
  List<KanjiEntry> dco_decode_list_kanji_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_kanji_entry).toList();
  }

  @protected
  List<LanguageSource> dco_decode_list_language_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_language_source).toList();
  }

  @protected
  List<LookupResult> dco_decode_list_lookup_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lookup_result).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SenseEntry> dco_decode_list_sense_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sense_entry).toList();
  }

  @protected
  List<Xref> dco_decode_list_xref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_xref).toList();
  }

  @protected
  LookupResult dco_decode_lookup_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LookupResult(
      entry: dco_decode_entry(arr[0]),
      matchType: dco_decode_match_type(arr[1]),
      matchKey: dco_decode_String(arr[2]),
      score: dco_decode_f_64(arr[3]),
      deinflection: dco_decode_opt_box_autoadd_deinflection_info(arr[4]),
    );
  }

  @protected
  MatchMode dco_decode_match_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatchMode.values[raw as int];
  }

  @protected
  MatchType dco_decode_match_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatchType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DeinflectionInfo? dco_decode_opt_box_autoadd_deinflection_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_deinflection_info(raw);
  }

  @protected
  Entry? dco_decode_opt_box_autoadd_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_entry(raw);
  }

  @protected
  LookupResult? dco_decode_opt_box_autoadd_lookup_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_lookup_result(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  QueryOptions dco_decode_query_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return QueryOptions(
      mode: dco_decode_match_mode(arr[0]),
      commonOnly: dco_decode_bool(arr[1]),
      pos: dco_decode_list_String(arr[2]),
      misc: dco_decode_list_String(arr[3]),
      field: dco_decode_list_String(arr[4]),
      dialect: dco_decode_list_String(arr[5]),
      limit: dco_decode_opt_box_autoadd_u_32(arr[6]),
      maxDistance: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  SenseEntry dco_decode_sense_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return SenseEntry(
      partOfSpeech: dco_decode_list_String(arr[0]),
      appliesToKanji: dco_decode_list_String(arr[1]),
      appliesToKana: dco_decode_list_String(arr[2]),
      related: dco_decode_list_xref(arr[3]),
      antonym: dco_decode_list_xref(arr[4]),
      field: dco_decode_list_String(arr[5]),
      dialect: dco_decode_list_String(arr[6]),
      misc: dco_decode_list_String(arr[7]),
      info: dco_decode_list_String(arr[8]),
      languageSource: dco_decode_list_language_source(arr[9]),
      gloss: dco_decode_list_gloss_entry(arr[10]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Xref dco_decode_xref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Xref(
      term: dco_decode_String(arr[0]),
      reading: dco_decode_opt_String(arr[1]),
      senseIndex: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  Dict
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DictImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Dict
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DictImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  Dict
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DictImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BatchResult sse_decode_batch_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_term = sse_decode_String(deserializer);
    var var_results = sse_decode_list_lookup_result(deserializer);
    return BatchResult(term: var_term, results: var_results);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeinflectionInfo sse_decode_box_autoadd_deinflection_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_deinflection_info(deserializer));
  }

  @protected
  Entry sse_decode_box_autoadd_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_entry(deserializer));
  }

  @protected
  InstallOptions sse_decode_box_autoadd_install_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_install_options(deserializer));
  }

  @protected
  LookupResult sse_decode_box_autoadd_lookup_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_lookup_result(deserializer));
  }

  @protected
  QueryOptions sse_decode_box_autoadd_query_options(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_query_options(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Xref sse_decode_box_autoadd_xref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_xref(deserializer));
  }

  @protected
  DataVersion sse_decode_data_version(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_formatVersion = sse_decode_u_32(deserializer);
    var var_jmdictVersion = sse_decode_String(deserializer);
    var var_generatedAt = sse_decode_String(deserializer);
    return DataVersion(
        formatVersion: var_formatVersion,
        jmdictVersion: var_jmdictVersion,
        generatedAt: var_generatedAt);
  }

  @protected
  DeinflectionInfo sse_decode_deinflection_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_originalForm = sse_decode_String(deserializer);
    var var_baseForm = sse_decode_String(deserializer);
    var var_rules = sse_decode_list_String(deserializer);
    return DeinflectionInfo(
        originalForm: var_originalForm,
        baseForm: var_baseForm,
        rules: var_rules);
  }

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_kanji = sse_decode_list_kanji_entry(deserializer);
    var var_kana = sse_decode_list_kana_entry(deserializer);
    var var_sense = sse_decode_list_sense_entry(deserializer);
    return Entry(
        id: var_id, kanji: var_kanji, kana: var_kana, sense: var_sense);
  }

  @protected
  Error sse_decode_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return Error_DataNotFound();
      case 1:
        var var_expected = sse_decode_u_32(deserializer);
        var var_found = sse_decode_u_32(deserializer);
        return Error_DataVersionMismatch(
            expected: var_expected, found: var_found);
      case 2:
        return Error_DataCorrupted();
      case 3:
        return Error_InvalidQuery();
      case 4:
        var var_message = sse_decode_String(deserializer);
        return Error_Io(message: var_message);
      case 5:
        return Error_Deserialization();
      case 6:
        var var_platform = sse_decode_String(deserializer);
        return Error_CacheDirRequired(platform: var_platform);
      case 7:
        return Error_CacheDirAlreadySet();
      case 8:
        var var_message = sse_decode_String(deserializer);
        return Error_Network(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GlossEntry sse_decode_gloss_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lang = sse_decode_String(deserializer);
    var var_gender = sse_decode_opt_String(deserializer);
    var var_glossType = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return GlossEntry(
        lang: var_lang,
        gender: var_gender,
        glossType: var_glossType,
        text: var_text);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InstallOptions sse_decode_install_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cacheDir = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_install_source(deserializer);
    var var_force = sse_decode_bool(deserializer);
    return InstallOptions(
        cacheDir: var_cacheDir, source: var_source, force: var_force);
  }

  @protected
  InstallSource sse_decode_install_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return InstallSource_OfficialRelease();
      case 1:
        var var_url = sse_decode_String(deserializer);
        return InstallSource_Url(url: var_url);
      case 2:
        var var_path = sse_decode_String(deserializer);
        return InstallSource_Tarball(path: var_path);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  KanaEntry sse_decode_kana_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_common = sse_decode_bool(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_appliesToKanji = sse_decode_list_String(deserializer);
    return KanaEntry(
        common: var_common,
        text: var_text,
        tags: var_tags,
        appliesToKanji: var_appliesToKanji);
  }

  @protected
  KanjiEntry sse_decode_kanji_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_common = sse_decode_bool(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return KanjiEntry(common: var_common, text: var_text, tags: var_tags);
  }

  @protected
  LanguageSource sse_decode_language_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lang = sse_decode_String(deserializer);
    var var_full = sse_decode_bool(deserializer);
    var var_wasei = sse_decode_bool(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    return LanguageSource(
        lang: var_lang, full: var_full, wasei: var_wasei, text: var_text);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BatchResult> sse_decode_list_batch_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BatchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_batch_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<Entry> sse_decode_list_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Entry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<GlossEntry> sse_decode_list_gloss_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GlossEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gloss_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<KanaEntry> sse_decode_list_kana_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KanaEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_kana_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<KanjiEntry> sse_decode_list_kanji_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KanjiEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_kanji_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<LanguageSource> sse_decode_list_language_source(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LanguageSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_language_source(deserializer));
    }
    return ans_;
  }

  @protected
  List<LookupResult> sse_decode_list_lookup_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LookupResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lookup_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SenseEntry> sse_decode_list_sense_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SenseEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sense_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<Xref> sse_decode_list_xref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Xref>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_xref(deserializer));
    }
    return ans_;
  }

  @protected
  LookupResult sse_decode_lookup_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entry = sse_decode_entry(deserializer);
    var var_matchType = sse_decode_match_type(deserializer);
    var var_matchKey = sse_decode_String(deserializer);
    var var_score = sse_decode_f_64(deserializer);
    var var_deinflection =
        sse_decode_opt_box_autoadd_deinflection_info(deserializer);
    return LookupResult(
        entry: var_entry,
        matchType: var_matchType,
        matchKey: var_matchKey,
        score: var_score,
        deinflection: var_deinflection);
  }

  @protected
  MatchMode sse_decode_match_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatchMode.values[inner];
  }

  @protected
  MatchType sse_decode_match_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatchType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DeinflectionInfo? sse_decode_opt_box_autoadd_deinflection_info(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_deinflection_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Entry? sse_decode_opt_box_autoadd_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_entry(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LookupResult? sse_decode_opt_box_autoadd_lookup_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_lookup_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QueryOptions sse_decode_query_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_match_mode(deserializer);
    var var_commonOnly = sse_decode_bool(deserializer);
    var var_pos = sse_decode_list_String(deserializer);
    var var_misc = sse_decode_list_String(deserializer);
    var var_field = sse_decode_list_String(deserializer);
    var var_dialect = sse_decode_list_String(deserializer);
    var var_limit = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxDistance = sse_decode_u_32(deserializer);
    return QueryOptions(
        mode: var_mode,
        commonOnly: var_commonOnly,
        pos: var_pos,
        misc: var_misc,
        field: var_field,
        dialect: var_dialect,
        limit: var_limit,
        maxDistance: var_maxDistance);
  }

  @protected
  SenseEntry sse_decode_sense_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_partOfSpeech = sse_decode_list_String(deserializer);
    var var_appliesToKanji = sse_decode_list_String(deserializer);
    var var_appliesToKana = sse_decode_list_String(deserializer);
    var var_related = sse_decode_list_xref(deserializer);
    var var_antonym = sse_decode_list_xref(deserializer);
    var var_field = sse_decode_list_String(deserializer);
    var var_dialect = sse_decode_list_String(deserializer);
    var var_misc = sse_decode_list_String(deserializer);
    var var_info = sse_decode_list_String(deserializer);
    var var_languageSource = sse_decode_list_language_source(deserializer);
    var var_gloss = sse_decode_list_gloss_entry(deserializer);
    return SenseEntry(
        partOfSpeech: var_partOfSpeech,
        appliesToKanji: var_appliesToKanji,
        appliesToKana: var_appliesToKana,
        related: var_related,
        antonym: var_antonym,
        field: var_field,
        dialect: var_dialect,
        misc: var_misc,
        info: var_info,
        languageSource: var_languageSource,
        gloss: var_gloss);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Xref sse_decode_xref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_term = sse_decode_String(deserializer);
    var var_reading = sse_decode_opt_String(deserializer);
    var var_senseIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    return Xref(
        term: var_term, reading: var_reading, senseIndex: var_senseIndex);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          Dict self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DictImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          Dict self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DictImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          Dict self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DictImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_batch_result(BatchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.term, serializer);
    sse_encode_list_lookup_result(self.results, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_deinflection_info(
      DeinflectionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_deinflection_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_entry(Entry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entry(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_install_options(
      InstallOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_install_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_lookup_result(
      LookupResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_lookup_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_query_options(
      QueryOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_query_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_xref(Xref self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_xref(self, serializer);
  }

  @protected
  void sse_encode_data_version(DataVersion self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.formatVersion, serializer);
    sse_encode_String(self.jmdictVersion, serializer);
    sse_encode_String(self.generatedAt, serializer);
  }

  @protected
  void sse_encode_deinflection_info(
      DeinflectionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.originalForm, serializer);
    sse_encode_String(self.baseForm, serializer);
    sse_encode_list_String(self.rules, serializer);
  }

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_list_kanji_entry(self.kanji, serializer);
    sse_encode_list_kana_entry(self.kana, serializer);
    sse_encode_list_sense_entry(self.sense, serializer);
  }

  @protected
  void sse_encode_error(Error self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Error_DataNotFound():
        sse_encode_i_32(0, serializer);
      case Error_DataVersionMismatch(
          expected: final expected,
          found: final found
        ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(expected, serializer);
        sse_encode_u_32(found, serializer);
      case Error_DataCorrupted():
        sse_encode_i_32(2, serializer);
      case Error_InvalidQuery():
        sse_encode_i_32(3, serializer);
      case Error_Io(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
      case Error_Deserialization():
        sse_encode_i_32(5, serializer);
      case Error_CacheDirRequired(platform: final platform):
        sse_encode_i_32(6, serializer);
        sse_encode_String(platform, serializer);
      case Error_CacheDirAlreadySet():
        sse_encode_i_32(7, serializer);
      case Error_Network(message: final message):
        sse_encode_i_32(8, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_gloss_entry(GlossEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lang, serializer);
    sse_encode_opt_String(self.gender, serializer);
    sse_encode_opt_String(self.glossType, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_install_options(
      InstallOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.cacheDir, serializer);
    sse_encode_install_source(self.source, serializer);
    sse_encode_bool(self.force, serializer);
  }

  @protected
  void sse_encode_install_source(InstallSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case InstallSource_OfficialRelease():
        sse_encode_i_32(0, serializer);
      case InstallSource_Url(url: final url):
        sse_encode_i_32(1, serializer);
        sse_encode_String(url, serializer);
      case InstallSource_Tarball(path: final path):
        sse_encode_i_32(2, serializer);
        sse_encode_String(path, serializer);
    }
  }

  @protected
  void sse_encode_kana_entry(KanaEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.common, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_list_String(self.appliesToKanji, serializer);
  }

  @protected
  void sse_encode_kanji_entry(KanjiEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.common, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_language_source(
      LanguageSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.lang, serializer);
    sse_encode_bool(self.full, serializer);
    sse_encode_bool(self.wasei, serializer);
    sse_encode_opt_String(self.text, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_batch_result(
      List<BatchResult> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_batch_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry(List<Entry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gloss_entry(
      List<GlossEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gloss_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_kana_entry(
      List<KanaEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_kana_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_kanji_entry(
      List<KanjiEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_kanji_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_language_source(
      List<LanguageSource> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_language_source(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lookup_result(
      List<LookupResult> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lookup_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sense_entry(
      List<SenseEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sense_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_xref(List<Xref> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_xref(item, serializer);
    }
  }

  @protected
  void sse_encode_lookup_result(LookupResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entry(self.entry, serializer);
    sse_encode_match_type(self.matchType, serializer);
    sse_encode_String(self.matchKey, serializer);
    sse_encode_f_64(self.score, serializer);
    sse_encode_opt_box_autoadd_deinflection_info(self.deinflection, serializer);
  }

  @protected
  void sse_encode_match_mode(MatchMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_match_type(MatchType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_deinflection_info(
      DeinflectionInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_deinflection_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_entry(Entry? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_entry(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_lookup_result(
      LookupResult? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_lookup_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_query_options(QueryOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_match_mode(self.mode, serializer);
    sse_encode_bool(self.commonOnly, serializer);
    sse_encode_list_String(self.pos, serializer);
    sse_encode_list_String(self.misc, serializer);
    sse_encode_list_String(self.field, serializer);
    sse_encode_list_String(self.dialect, serializer);
    sse_encode_opt_box_autoadd_u_32(self.limit, serializer);
    sse_encode_u_32(self.maxDistance, serializer);
  }

  @protected
  void sse_encode_sense_entry(SenseEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.partOfSpeech, serializer);
    sse_encode_list_String(self.appliesToKanji, serializer);
    sse_encode_list_String(self.appliesToKana, serializer);
    sse_encode_list_xref(self.related, serializer);
    sse_encode_list_xref(self.antonym, serializer);
    sse_encode_list_String(self.field, serializer);
    sse_encode_list_String(self.dialect, serializer);
    sse_encode_list_String(self.misc, serializer);
    sse_encode_list_String(self.info, serializer);
    sse_encode_list_language_source(self.languageSource, serializer);
    sse_encode_list_gloss_entry(self.gloss, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_xref(Xref self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.term, serializer);
    sse_encode_opt_String(self.reading, serializer);
    sse_encode_opt_box_autoadd_u_32(self.senseIndex, serializer);
  }
}

@sealed
class DictImpl extends RustOpaque implements Dict {
  // Not to be used by end users
  DictImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DictImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Dict,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Dict,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_DictPtr,
  );

  Future<BigInt> entryCount() =>
      RustLib.instance.api.crateApiDictionaryDictEntryCount(
        that: this,
      );

  Future<Entry?> get_({required BigInt seqId}) =>
      RustLib.instance.api.crateApiDictionaryDictGet(that: this, seqId: seqId);

  Future<List<Entry>> iterEntries(
          {required BigInt start, required BigInt count}) =>
      RustLib.instance.api.crateApiDictionaryDictIterEntries(
          that: this, start: start, count: count);

  Future<List<BatchResult>> lookupBatch(
          {required List<String> terms, required QueryOptions options}) =>
      RustLib.instance.api.crateApiDictionaryDictLookupBatch(
          that: this, terms: terms, options: options);

  Future<LookupResult?> lookupById({required String jmdictId}) =>
      RustLib.instance.api
          .crateApiDictionaryDictLookupById(that: this, jmdictId: jmdictId);

  Future<List<LookupResult>> lookupExact({required String term}) =>
      RustLib.instance.api
          .crateApiDictionaryDictLookupExact(that: this, term: term);

  Future<List<LookupResult>> lookupExactWithDeinflection(
          {required String term}) =>
      RustLib.instance.api.crateApiDictionaryDictLookupExactWithDeinflection(
          that: this, term: term);

  Future<List<LookupResult>> lookupGloss({required String query}) =>
      RustLib.instance.api
          .crateApiDictionaryDictLookupGloss(that: this, query: query);

  Future<List<LookupResult>> lookupPartial({required String prefix}) =>
      RustLib.instance.api
          .crateApiDictionaryDictLookupPartial(that: this, prefix: prefix);

  Future<List<LookupResult>> lookupWithOptions(
          {required String term, required QueryOptions options}) =>
      RustLib.instance.api.crateApiDictionaryDictLookupWithOptions(
          that: this, term: term, options: options);

  Future<List<LookupResult>> resolveXref({required Xref xref}) =>
      RustLib.instance.api
          .crateApiDictionaryDictResolveXref(that: this, xref: xref);

  Future<DataVersion> version() =>
      RustLib.instance.api.crateApiDictionaryDictVersion(
        that: this,
      );
}
