// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dictionary.dart';
import 'api/error.dart';
import 'api/install.dart';
import 'api/model.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DictPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDictPtr;

  @protected
  Dict
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          dynamic raw);

  @protected
  Dict
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          dynamic raw);

  @protected
  Dict
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BatchResult dco_decode_batch_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeinflectionInfo dco_decode_box_autoadd_deinflection_info(dynamic raw);

  @protected
  Entry dco_decode_box_autoadd_entry(dynamic raw);

  @protected
  InstallOptions dco_decode_box_autoadd_install_options(dynamic raw);

  @protected
  LookupResult dco_decode_box_autoadd_lookup_result(dynamic raw);

  @protected
  QueryOptions dco_decode_box_autoadd_query_options(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Xref dco_decode_box_autoadd_xref(dynamic raw);

  @protected
  DataVersion dco_decode_data_version(dynamic raw);

  @protected
  DeinflectionInfo dco_decode_deinflection_info(dynamic raw);

  @protected
  Entry dco_decode_entry(dynamic raw);

  @protected
  Error dco_decode_error(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GlossEntry dco_decode_gloss_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InstallOptions dco_decode_install_options(dynamic raw);

  @protected
  InstallSource dco_decode_install_source(dynamic raw);

  @protected
  KanaEntry dco_decode_kana_entry(dynamic raw);

  @protected
  KanjiEntry dco_decode_kanji_entry(dynamic raw);

  @protected
  LanguageSource dco_decode_language_source(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BatchResult> dco_decode_list_batch_result(dynamic raw);

  @protected
  List<Entry> dco_decode_list_entry(dynamic raw);

  @protected
  List<GlossEntry> dco_decode_list_gloss_entry(dynamic raw);

  @protected
  List<KanaEntry> dco_decode_list_kana_entry(dynamic raw);

  @protected
  List<KanjiEntry> dco_decode_list_kanji_entry(dynamic raw);

  @protected
  List<LanguageSource> dco_decode_list_language_source(dynamic raw);

  @protected
  List<LookupResult> dco_decode_list_lookup_result(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SenseEntry> dco_decode_list_sense_entry(dynamic raw);

  @protected
  List<Xref> dco_decode_list_xref(dynamic raw);

  @protected
  LookupResult dco_decode_lookup_result(dynamic raw);

  @protected
  MatchMode dco_decode_match_mode(dynamic raw);

  @protected
  MatchType dco_decode_match_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DeinflectionInfo? dco_decode_opt_box_autoadd_deinflection_info(dynamic raw);

  @protected
  Entry? dco_decode_opt_box_autoadd_entry(dynamic raw);

  @protected
  LookupResult? dco_decode_opt_box_autoadd_lookup_result(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  QueryOptions dco_decode_query_options(dynamic raw);

  @protected
  SenseEntry dco_decode_sense_entry(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Xref dco_decode_xref(dynamic raw);

  @protected
  Dict
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          SseDeserializer deserializer);

  @protected
  Dict
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          SseDeserializer deserializer);

  @protected
  Dict
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BatchResult sse_decode_batch_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeinflectionInfo sse_decode_box_autoadd_deinflection_info(
      SseDeserializer deserializer);

  @protected
  Entry sse_decode_box_autoadd_entry(SseDeserializer deserializer);

  @protected
  InstallOptions sse_decode_box_autoadd_install_options(
      SseDeserializer deserializer);

  @protected
  LookupResult sse_decode_box_autoadd_lookup_result(
      SseDeserializer deserializer);

  @protected
  QueryOptions sse_decode_box_autoadd_query_options(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Xref sse_decode_box_autoadd_xref(SseDeserializer deserializer);

  @protected
  DataVersion sse_decode_data_version(SseDeserializer deserializer);

  @protected
  DeinflectionInfo sse_decode_deinflection_info(SseDeserializer deserializer);

  @protected
  Entry sse_decode_entry(SseDeserializer deserializer);

  @protected
  Error sse_decode_error(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GlossEntry sse_decode_gloss_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InstallOptions sse_decode_install_options(SseDeserializer deserializer);

  @protected
  InstallSource sse_decode_install_source(SseDeserializer deserializer);

  @protected
  KanaEntry sse_decode_kana_entry(SseDeserializer deserializer);

  @protected
  KanjiEntry sse_decode_kanji_entry(SseDeserializer deserializer);

  @protected
  LanguageSource sse_decode_language_source(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BatchResult> sse_decode_list_batch_result(SseDeserializer deserializer);

  @protected
  List<Entry> sse_decode_list_entry(SseDeserializer deserializer);

  @protected
  List<GlossEntry> sse_decode_list_gloss_entry(SseDeserializer deserializer);

  @protected
  List<KanaEntry> sse_decode_list_kana_entry(SseDeserializer deserializer);

  @protected
  List<KanjiEntry> sse_decode_list_kanji_entry(SseDeserializer deserializer);

  @protected
  List<LanguageSource> sse_decode_list_language_source(
      SseDeserializer deserializer);

  @protected
  List<LookupResult> sse_decode_list_lookup_result(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SenseEntry> sse_decode_list_sense_entry(SseDeserializer deserializer);

  @protected
  List<Xref> sse_decode_list_xref(SseDeserializer deserializer);

  @protected
  LookupResult sse_decode_lookup_result(SseDeserializer deserializer);

  @protected
  MatchMode sse_decode_match_mode(SseDeserializer deserializer);

  @protected
  MatchType sse_decode_match_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DeinflectionInfo? sse_decode_opt_box_autoadd_deinflection_info(
      SseDeserializer deserializer);

  @protected
  Entry? sse_decode_opt_box_autoadd_entry(SseDeserializer deserializer);

  @protected
  LookupResult? sse_decode_opt_box_autoadd_lookup_result(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  QueryOptions sse_decode_query_options(SseDeserializer deserializer);

  @protected
  SenseEntry sse_decode_sense_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Xref sse_decode_xref(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          Dict self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          Dict self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
          Dict self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_batch_result(BatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_deinflection_info(
      DeinflectionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entry(Entry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_install_options(
      InstallOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lookup_result(
      LookupResult self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_query_options(
      QueryOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_xref(Xref self, SseSerializer serializer);

  @protected
  void sse_encode_data_version(DataVersion self, SseSerializer serializer);

  @protected
  void sse_encode_deinflection_info(
      DeinflectionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_entry(Entry self, SseSerializer serializer);

  @protected
  void sse_encode_error(Error self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_gloss_entry(GlossEntry self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_install_options(
      InstallOptions self, SseSerializer serializer);

  @protected
  void sse_encode_install_source(InstallSource self, SseSerializer serializer);

  @protected
  void sse_encode_kana_entry(KanaEntry self, SseSerializer serializer);

  @protected
  void sse_encode_kanji_entry(KanjiEntry self, SseSerializer serializer);

  @protected
  void sse_encode_language_source(
      LanguageSource self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_batch_result(
      List<BatchResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entry(List<Entry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gloss_entry(
      List<GlossEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_kana_entry(
      List<KanaEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_kanji_entry(
      List<KanjiEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_language_source(
      List<LanguageSource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lookup_result(
      List<LookupResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_sense_entry(
      List<SenseEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_xref(List<Xref> self, SseSerializer serializer);

  @protected
  void sse_encode_lookup_result(LookupResult self, SseSerializer serializer);

  @protected
  void sse_encode_match_mode(MatchMode self, SseSerializer serializer);

  @protected
  void sse_encode_match_type(MatchType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_deinflection_info(
      DeinflectionInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entry(Entry? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lookup_result(
      LookupResult? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_query_options(QueryOptions self, SseSerializer serializer);

  @protected
  void sse_encode_sense_entry(SenseEntry self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_xref(Xref self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDictPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_jmdict_fast_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDictPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDictPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_jmdict_fast_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDict =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDictPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
