// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'install.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Dict>>
abstract class Dict implements RustOpaqueInterface {
  Future<BigInt> entryCount();

  Future<Entry?> get_({required BigInt seqId});

  /// Download the official release tarball into the platform cache
  /// (via `init_sdk_cache_dir` or `InstallOptions.cacheDir`) and load
  /// it. No-op on warm cache.
  static Future<Dict> install() =>
      RustLib.instance.api.crateApiDictionaryDictInstall();

  static Future<Dict> installFromTarball({required String path}) =>
      RustLib.instance.api.crateApiDictionaryDictInstallFromTarball(path: path);

  static Future<Dict> installFromUrl({required String url}) =>
      RustLib.instance.api.crateApiDictionaryDictInstallFromUrl(url: url);

  static Future<Dict> installWith({required InstallOptions options}) =>
      RustLib.instance.api.crateApiDictionaryDictInstallWith(options: options);

  Future<List<Entry>> iterEntries(
      {required BigInt start, required BigInt count});

  static Future<Dict> load({required String path}) =>
      RustLib.instance.api.crateApiDictionaryDictLoad(path: path);

  static Future<Dict> loadDefault() =>
      RustLib.instance.api.crateApiDictionaryDictLoadDefault();

  Future<List<BatchResult>> lookupBatch(
      {required List<String> terms, required QueryOptions options});

  Future<LookupResult?> lookupById({required String jmdictId});

  Future<List<LookupResult>> lookupExact({required String term});

  Future<List<LookupResult>> lookupExactWithDeinflection(
      {required String term});

  Future<List<LookupResult>> lookupGloss({required String query});

  Future<List<LookupResult>> lookupPartial({required String prefix});

  Future<List<LookupResult>> lookupWithOptions(
      {required String term, required QueryOptions options});

  Future<List<LookupResult>> resolveXref({required Xref xref});

  Future<DataVersion> version();
}
