// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`, `from`

@freezed
sealed class Error with _$Error implements FrbException {
  const Error._();

  const factory Error.dataNotFound() = Error_DataNotFound;
  const factory Error.dataVersionMismatch({
    required int expected,
    required int found,
  }) = Error_DataVersionMismatch;
  const factory Error.dataCorrupted() = Error_DataCorrupted;
  const factory Error.invalidQuery() = Error_InvalidQuery;
  const factory Error.io({
    required String message,
  }) = Error_Io;
  const factory Error.deserialization() = Error_Deserialization;

  /// `Dict::install*` needs a cache directory and the host hasn't
  /// registered one. `platform` carries the target_os string so the
  /// Dart side can branch on "ios" / "android" / "wasm" without parsing
  /// the message.
  const factory Error.cacheDirRequired({
    required String platform,
  }) = Error_CacheDirRequired;

  /// `init_sdk_cache_dir` was called twice; the cache root is one-shot.
  const factory Error.cacheDirAlreadySet() = Error_CacheDirAlreadySet;

  /// Download or extract failed (timeout, non-2xx, oversize, …).
  const factory Error.network({
    required String message,
  }) = Error_Network;
}
