// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'install.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

/// Register the process-global cache directory for `Dict.install*`. On
/// Flutter this is mandatory before any install call — the host obtains
/// a writable path via `path_provider.getApplicationSupportDirectory()`
/// (or platform-specific equivalent) and passes it in once.
///
/// First call wins; subsequent calls return [`Error::CacheDirAlreadySet`].
Future<void> initSdkCacheDir({required String path}) =>
    RustLib.instance.api.crateApiInstallInitSdkCacheDir(path: path);

/// Options record for `Dict.installWith(...)`. POD; all fields optional.
class InstallOptions {
  /// Cache root for this call. Wins over `init_sdk_cache_dir` and the
  /// platform default.
  final String? cacheDir;
  final InstallSource source;

  /// Re-extract even when the cache appears complete.
  final bool force;

  const InstallOptions({
    this.cacheDir,
    required this.source,
    required this.force,
  });

  static Future<InstallOptions> default_() =>
      RustLib.instance.api.crateApiInstallInstallOptionsDefault();

  @override
  int get hashCode => cacheDir.hashCode ^ source.hashCode ^ force.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallOptions &&
          runtimeType == other.runtimeType &&
          cacheDir == other.cacheDir &&
          source == other.source &&
          force == other.force;
}

@freezed
sealed class InstallSource with _$InstallSource {
  const InstallSource._();

  /// The GitHub release tarball for this crate / JMdict / format version.
  const factory InstallSource.officialRelease() = InstallSource_OfficialRelease;

  /// Any `.tar.gz` reachable over HTTPS.
  const factory InstallSource.url({
    required String url,
  }) = InstallSource_Url;

  /// A `.tar.gz` already on the local filesystem.
  const factory InstallSource.tarball({
    required String path,
  }) = InstallSource_Tarball;

  static Future<InstallSource> default_() =>
      RustLib.instance.api.crateApiInstallInstallSourceDefault();
}
