// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class BatchResult {
  final String term;
  final List<LookupResult> results;

  const BatchResult({
    required this.term,
    required this.results,
  });

  @override
  int get hashCode => term.hashCode ^ results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchResult &&
          runtimeType == other.runtimeType &&
          term == other.term &&
          results == other.results;
}

class DataVersion {
  final int formatVersion;
  final String jmdictVersion;
  final String generatedAt;

  const DataVersion({
    required this.formatVersion,
    required this.jmdictVersion,
    required this.generatedAt,
  });

  @override
  int get hashCode =>
      formatVersion.hashCode ^ jmdictVersion.hashCode ^ generatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataVersion &&
          runtimeType == other.runtimeType &&
          formatVersion == other.formatVersion &&
          jmdictVersion == other.jmdictVersion &&
          generatedAt == other.generatedAt;
}

class DeinflectionInfo {
  final String originalForm;
  final String baseForm;
  final List<String> rules;

  const DeinflectionInfo({
    required this.originalForm,
    required this.baseForm,
    required this.rules,
  });

  @override
  int get hashCode =>
      originalForm.hashCode ^ baseForm.hashCode ^ rules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeinflectionInfo &&
          runtimeType == other.runtimeType &&
          originalForm == other.originalForm &&
          baseForm == other.baseForm &&
          rules == other.rules;
}

class Entry {
  final String id;
  final List<KanjiEntry> kanji;
  final List<KanaEntry> kana;
  final List<SenseEntry> sense;

  const Entry({
    required this.id,
    required this.kanji,
    required this.kana,
    required this.sense,
  });

  @override
  int get hashCode =>
      id.hashCode ^ kanji.hashCode ^ kana.hashCode ^ sense.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Entry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kanji == other.kanji &&
          kana == other.kana &&
          sense == other.sense;
}

class GlossEntry {
  final String lang;
  final String? gender;
  final String? glossType;
  final String text;

  const GlossEntry({
    required this.lang,
    this.gender,
    this.glossType,
    required this.text,
  });

  @override
  int get hashCode =>
      lang.hashCode ^ gender.hashCode ^ glossType.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossEntry &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          gender == other.gender &&
          glossType == other.glossType &&
          text == other.text;
}

class KanaEntry {
  final bool common;
  final String text;
  final List<String> tags;
  final List<String> appliesToKanji;

  const KanaEntry({
    required this.common,
    required this.text,
    required this.tags,
    required this.appliesToKanji,
  });

  @override
  int get hashCode =>
      common.hashCode ^ text.hashCode ^ tags.hashCode ^ appliesToKanji.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KanaEntry &&
          runtimeType == other.runtimeType &&
          common == other.common &&
          text == other.text &&
          tags == other.tags &&
          appliesToKanji == other.appliesToKanji;
}

class KanjiEntry {
  final bool common;
  final String text;
  final List<String> tags;

  const KanjiEntry({
    required this.common,
    required this.text,
    required this.tags,
  });

  @override
  int get hashCode => common.hashCode ^ text.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KanjiEntry &&
          runtimeType == other.runtimeType &&
          common == other.common &&
          text == other.text &&
          tags == other.tags;
}

class LanguageSource {
  final String lang;
  final bool full;
  final bool wasei;
  final String? text;

  const LanguageSource({
    required this.lang,
    required this.full,
    required this.wasei,
    this.text,
  });

  @override
  int get hashCode =>
      lang.hashCode ^ full.hashCode ^ wasei.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LanguageSource &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          full == other.full &&
          wasei == other.wasei &&
          text == other.text;
}

class LookupResult {
  final Entry entry;
  final MatchType matchType;
  final String matchKey;
  final double score;
  final DeinflectionInfo? deinflection;

  const LookupResult({
    required this.entry,
    required this.matchType,
    required this.matchKey,
    required this.score,
    this.deinflection,
  });

  @override
  int get hashCode =>
      entry.hashCode ^
      matchType.hashCode ^
      matchKey.hashCode ^
      score.hashCode ^
      deinflection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LookupResult &&
          runtimeType == other.runtimeType &&
          entry == other.entry &&
          matchType == other.matchType &&
          matchKey == other.matchKey &&
          score == other.score &&
          deinflection == other.deinflection;
}

enum MatchMode {
  exact,
  prefix,
  deinflect,
  fuzzy,
  ;
}

enum MatchType {
  exact,
  prefix,
  deinflected,
  fuzzy,
  gloss,
  ;
}

class QueryOptions {
  final MatchMode mode;
  final bool commonOnly;
  final List<String> pos;
  final List<String> misc;
  final List<String> field;
  final List<String> dialect;
  final int? limit;
  final int maxDistance;

  const QueryOptions({
    required this.mode,
    required this.commonOnly,
    required this.pos,
    required this.misc,
    required this.field,
    required this.dialect,
    this.limit,
    required this.maxDistance,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      commonOnly.hashCode ^
      pos.hashCode ^
      misc.hashCode ^
      field.hashCode ^
      dialect.hashCode ^
      limit.hashCode ^
      maxDistance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryOptions &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          commonOnly == other.commonOnly &&
          pos == other.pos &&
          misc == other.misc &&
          field == other.field &&
          dialect == other.dialect &&
          limit == other.limit &&
          maxDistance == other.maxDistance;
}

class SenseEntry {
  final List<String> partOfSpeech;
  final List<String> appliesToKanji;
  final List<String> appliesToKana;
  final List<Xref> related;
  final List<Xref> antonym;
  final List<String> field;
  final List<String> dialect;
  final List<String> misc;
  final List<String> info;
  final List<LanguageSource> languageSource;
  final List<GlossEntry> gloss;

  const SenseEntry({
    required this.partOfSpeech,
    required this.appliesToKanji,
    required this.appliesToKana,
    required this.related,
    required this.antonym,
    required this.field,
    required this.dialect,
    required this.misc,
    required this.info,
    required this.languageSource,
    required this.gloss,
  });

  @override
  int get hashCode =>
      partOfSpeech.hashCode ^
      appliesToKanji.hashCode ^
      appliesToKana.hashCode ^
      related.hashCode ^
      antonym.hashCode ^
      field.hashCode ^
      dialect.hashCode ^
      misc.hashCode ^
      info.hashCode ^
      languageSource.hashCode ^
      gloss.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenseEntry &&
          runtimeType == other.runtimeType &&
          partOfSpeech == other.partOfSpeech &&
          appliesToKanji == other.appliesToKanji &&
          appliesToKana == other.appliesToKana &&
          related == other.related &&
          antonym == other.antonym &&
          field == other.field &&
          dialect == other.dialect &&
          misc == other.misc &&
          info == other.info &&
          languageSource == other.languageSource &&
          gloss == other.gloss;
}

class Xref {
  final String term;
  final String? reading;
  final int? senseIndex;

  const Xref({
    required this.term,
    this.reading,
    this.senseIndex,
  });

  @override
  int get hashCode => term.hashCode ^ reading.hashCode ^ senseIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Xref &&
          runtimeType == other.runtimeType &&
          term == other.term &&
          reading == other.reading &&
          senseIndex == other.senseIndex;
}
