// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle`, `into_demo_hit`

/// Load the dictionary from `data_dir`. Must be called before any lookup.
/// `async` so FRB runs the mmap on a worker thread — the first call
/// touches every FST file.
Future<BigInt> initDictionary({required String dataDir}) =>
    RustLib.instance.api.crateApiSimpleInitDictionary(dataDir: dataDir);

/// Whether `init_dictionary` has been called and succeeded.
bool isDictionaryReady() =>
    RustLib.instance.api.crateApiSimpleIsDictionaryReady();

/// Exact match across kana/kanji/romaji. Sync because an FST hit is
/// microsecond-scale — no point making the Dart side `await` it.
List<DemoHit> lookupExact({required String term}) =>
    RustLib.instance.api.crateApiSimpleLookupExact(term: term);

/// Prefix search ("starts with").
List<DemoHit> lookupPartial({required String prefix}) =>
    RustLib.instance.api.crateApiSimpleLookupPartial(prefix: prefix);

/// Reverse lookup by English gloss. `async` because posting-list
/// intersection over common tokens can run thousands of entries.
Future<List<DemoHit>> lookupGloss({required String query}) =>
    RustLib.instance.api.crateApiSimpleLookupGloss(query: query);

/// Compact lookup row designed for the demo screen: just enough to render
/// a list entry. The full `LookupResult` is reachable through the
/// `jmdict-fast-flutter` crate directly for apps that need it.
class DemoHit {
  final String? kanji;
  final String? kana;
  final String? gloss;

  const DemoHit({this.kanji, this.kana, this.gloss});

  @override
  int get hashCode => kanji.hashCode ^ kana.hashCode ^ gloss.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DemoHit &&
          runtimeType == other.runtimeType &&
          kanji == other.kanji &&
          kana == other.kana &&
          gloss == other.gloss;
}
